{
  "hash": "c5d3bc808e8e3959ced21a907cd86385",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"practice_1\"\nformat: html\n---\n\n## Load libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(ggplot2)\n```\n:::\n\n\n## Ingest the data from [GitHub SMM635 repo][1]\n\nThe dataset comes from Kaggle's [Google Play Store Apps][0] project. Please refer\nto the project description for details concerning the data gathering and structuring\naspects.\n\nThe project comprises two data tables: app- and review-level data. We will focus \non the former. \n\n[0]: https://www.kaggle.com/datasets/lava18/google-play-store-apps\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_source <- \"https://raw.githubusercontent.com/simoneSantoni/data-viz-smm635/refs/heads/master/data/googleplaystore.csv\"\napps <- read_csv(data_source)\n```\n:::\n\n\n[1]:https://raw.githubusercontent.com/simoneSantoni/data-viz-smm635/refs/heads/master/data/googleplaystore.csv\n\n## Familiarize with data\n\n\n### Key Figures\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspec(apps)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncols(\n  App = col_character(),\n  Category = col_character(),\n  Rating = col_double(),\n  Reviews = col_double(),\n  Size = col_character(),\n  Installs = col_character(),\n  Type = col_character(),\n  Price = col_character(),\n  `Content Rating` = col_character(),\n  Genres = col_character(),\n  `Last Updated` = col_character(),\n  `Current Ver` = col_character(),\n  `Android Ver` = col_character()\n)\n```\n\n\n:::\n:::\n\n\n### Data Preview\n\n\n::: {.cell}\n\n```{.r .cell-code}\napps\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10,841 × 13\n   App       Category Rating Reviews Size  Installs Type  Price `Content Rating`\n   <chr>     <chr>     <dbl>   <dbl> <chr> <chr>    <chr> <chr> <chr>           \n 1 Photo Ed… ART_AND…    4.1     159 19M   10,000+  Free  0     Everyone        \n 2 Coloring… ART_AND…    3.9     967 14M   500,000+ Free  0     Everyone        \n 3 U Launch… ART_AND…    4.7   87510 8.7M  5,000,0… Free  0     Everyone        \n 4 Sketch -… ART_AND…    4.5  215644 25M   50,000,… Free  0     Teen            \n 5 Pixel Dr… ART_AND…    4.3     967 2.8M  100,000+ Free  0     Everyone        \n 6 Paper fl… ART_AND…    4.4     167 5.6M  50,000+  Free  0     Everyone        \n 7 Smoke Ef… ART_AND…    3.8     178 19M   50,000+  Free  0     Everyone        \n 8 Infinite… ART_AND…    4.1   36815 29M   1,000,0… Free  0     Everyone        \n 9 Garden C… ART_AND…    4.4   13791 33M   1,000,0… Free  0     Everyone        \n10 Kids Pai… ART_AND…    4.7     121 3.1M  10,000+  Free  0     Everyone        \n# ℹ 10,831 more rows\n# ℹ 4 more variables: Genres <chr>, `Last Updated` <chr>, `Current Ver` <chr>,\n#   `Android Ver` <chr>\n```\n\n\n:::\n:::\n\n\n### Variable Definitions                                                                                                            \n#### App                                                                                                                         \n- **Type:** Text (String)                                                                                                            \n- **Description:** Name of the application                                                                                           \n- **Example Values:**                                                                                                                \n  - \"Photo Editor & Candy Camera & Grid & ScrapBook\"                                                                                 \n  - \"Coloring book moana\"                                                                                                            \n  - \"U Launcher Lite – FREE Live Cool Themes, Hide Apps\"                                                                             \n  - \"Sketch - Draw & Paint\"                                                                                                          \n- **Missing Values:** Expected to be minimal/none (key identifier)                                                                   \n- **Notes:** May contain special characters, emojis, and version information                                                         \n\n#### Category                                                                                                                     \n- **Type:** Categorical (String)                                                                                                     \n- **Description:** Primary category classification of the app on Google Play Store                                                   \n- **Unique Categories:** 33 main categories + some miscoded entries                                                                  \n- **Data Quality Issues:** Contains miscoded entries (app names/descriptions appearing as category values)                           \n                                                                                                                                     \n#### Rating                                                                                                                       \n- **Type:** Numeric (Float)                                                                                                          \n- **Description:** Average user rating on a scale of 1.0 to 5.0                                                                      \n- **Range:** 1.0 - 5.0 (expected)                                                                                                    \n- **Example Values:** 4.1, 3.9, 4.7, 4.5                                                                                             \n- **Missing Values:** Expected to be present for apps with no ratings                                                                \n- **Notes:** Higher values indicate better user satisfaction                                                                         \n                                                                                                                                     \n#### Reviews                                                                                                                      \n- **Type:** Numeric (Integer)                                                                                                        \n- **Description:** Total number of user reviews submitted for the app                                                                \n- **Example Values:** 159, 967, 87510, 215644                                                                                        \n- **Range:** 0 to millions                                                                                                           \n- **Notes:** Indicator of app popularity and user engagement                                                                         \n                                                                                                                                     \n#### Size                                                                                                                         \n- **Type:** Text (String with units)                                                                                                 \n- **Description:** Size of the application                                                                                           \n- **Format:** Number followed by unit (M for megabytes, k for kilobytes)                                                             \n- **Example Values:** \"19M\", \"14M\", \"8.7M\", \"25M\"                                                                                    \n- **Special Values:**                                                                                                                \n  - \"Varies with device\" - size depends on device specifications                                                                     \n- **Notes:** Requires parsing to convert to numeric format for analysis                                                              \n                                                                                                                                     \n#### Installs                                                                                                                     \n- **Type:** Categorical (String)                                                                                                     \n- **Description:** Number of times the app has been installed (in ranges)                                                            \n- **Format:** Comma-separated numbers with plus sign                                                                                 \n- **Example Values:** \"10,000+\", \"500,000+\", \"5,000,000+\", \"50,000,000+\"                                                             \n- **Notes:** Requires parsing to convert to numeric format; provides order of magnitude rather than exact counts                     \n                                                                                                                                     \n#### Type                                                                                                                         \n- **Type:** Binary Categorical (String)                                                                                              \n- **Description:** Whether the app is free or paid                                                                                   \n- **Distribution:** Majority of apps are free                                                                                        \n- **Notes:** Some data quality issues with miscoded entries                                                                          \n                                                                                                                                     \n#### Price                                                                                                                        \n- **Type:** Text (String with currency symbol)                                                                                       \n- **Description:** Price of the app (if paid)                                                                                        \n- **Format:** Usually \"0\" for free apps or \"$X.XX\" for paid apps                                                                     \n- **Example Values:** \"0\", \"$0.99\", \"$2.99\", \"$4.99\"                                                                                 \n- **Notes:**                                                                                                                         \n  - Free apps should have \"0\" value                                                                                                  \n  - Requires parsing to remove currency symbol for numeric analysis                                                                  \n  - Currency is primarily USD ($)                                                                                                    \n                                                                                                                                     \n#### Content Rating                                                                                                               \n- **Type:** Categorical (String)                                                                                                     \n- **Description:** Age group suitability rating for the app                                                                          \n- **Standard Values:**                                                                                                               \n  - \"Everyone\" - Suitable for all ages                                                                                               \n  - \"Everyone 10+\" - Suitable for ages 10 and up                                                                                     \n  - \"Teen\" - Suitable for ages 13 and up                                                                                             \n  - \"Mature 17+\" - Suitable for ages 17 and up                                                                                       \n  - \"Adults only 18+\" - Suitable for ages 18 and up                                                                                  \n  - \"Unrated\" - No rating assigned                                                                                                   \n- **Example Values:** \"Everyone\", \"Teen\"                                                                                             \n- **Notes:** Follows Google Play Store's content rating system                                                                       \n                                                                                                                                     \n#### Genres                                                                                                                      \n- **Type:** Text (String, may contain multiple values)                                                                               \n- **Description:** Detailed genre classification (may include subcategories)                                                         \n- **Format:** Primary genre, sometimes followed by semicolon and secondary genre                                                     \n- **Example Values:**                                                                                                                \n  - \"Art & Design\"                                                                                                                   \n  - \"Art & Design;Pretend Play\"                                                                                                      \n- **Notes:** More specific than Category field; can contain multiple genres separated by semicolons                                  \n                                                                                                                                     \n#### Last Updated                                                                                                                \n- **Type:** Date (String)                                                                                                            \n- **Description:** Date when the app was last updated                                                                                \n- **Format:** \"Month Day, Year\" (e.g., \"January 7, 2018\")                                                                            \n- **Example Values:** \"January 7, 2018\", \"January 15, 2018\", \"August 1, 2018\", \"June 8, 2018\"                                        \n- **Notes:** Can be used to assess app maintenance and developer activity; requires date parsing for analysis                        \n                                                                                                                                     \n#### Current Ver                                                                                                                 \n- **Type:** Text (String)                                                                                                            \n- **Description:** Current version of the application                                                                                \n- **Format:** Varies widely (semantic versioning, numeric versions, descriptive text)                                                \n- **Example Values:** \"1.0.0\", \"2.0.0\", \"1.2.4\", \"Varies with device\"                                                                \n- **Special Values:** \"Varies with device\" - version depends on device                                                               \n- **Notes:** No standardized format across apps                                                                                      \n                                                                                                                                     \n#### Android Ver                                                                                                                 \n- **Type:** Text (String)                                                                                                            \n- **Description:** Minimum Android version required to run the app                                                                   \n- **Format:** Version number followed by \"and up\"                                                                                    \n- **Example Values:** \"4.0.3 and up\", \"4.2 and up\"                                                                                   \n- **Special Values:** \"Varies with device\" - requirement depends on device                                                           \n- **Notes:** Indicates app compatibility range      \n\n## Data Visualization\n\n### Univariate Charts\n\n#### Categorical Variables\n\n@fig-bar-chart shows possible data quality issues: some cases present value $0$,\nwhose meaning is unclear in the context of this variable; other cases present \nmissing values, displayed as $NaN$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = apps, mapping = aes(x = Type)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![Counts of apps by pricing type](practice_1_files/figure-html/fig-bar-chart-1.png){#fig-bar-chart width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = apps, mapping = aes(x = \"\", fill = Type)) +\n  geom_bar(width = 1) +\n  coord_polar(theta = \"y\") +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![Pie charts can also be used to visualize categorical variables' univariate distributions](practice_1_files/figure-html/fig-pie-chart-1.png){#fig-pie-chart width=672}\n:::\n:::\n\n\n",
    "supporting": [
      "practice_1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}