---
author: Simone Santoni
date: 2024-10-31
title: Text annotations
abstract: This notebook shows how to add and manipulate companion text to the hard-core part of a chart, namely, data, aestehtics, and themes.
abstract-title: Abstract
format:
  html:
    code-fold: true
---

## Notebok setup

### Load libraries

```{r}
library(readr)
library(ggplot2)
library(hrbrthemes)
library(gcookbook)
```

### Load data

```{r}
df <- read_csv("/home/simone/githubRepos/data-viz-smm635/data/imdb/data.csv")
df
```

## A sample scatter diagram

```{r}
#| label: fig-barebon
p <- ggplot(df, aes(x = averageRating, y = numVotes))
p + geom_point()
```

### Change default theme and redo the chart

```{r}
#| label: fig-themeipsum
#| fig-cap: "Theme is 'theme_ipsum_ps()' from 'hrbrthemes'"
theme_set(theme_ipsum_ps())
p + geom_point() + theme_ipsum()
```

```{r}
#| label: fig-withlabels
#| fig-cap: "Now with proper text annotations"
p + geom_point() + 
  labs(
    x="Average rating", 
    y="Number of votes", 
    title="A scatter diagram", 
    subtitle="Theme is theme_ipsum_ps()", 
    caption="Fig. 1 ― That's cool!"
  )
```
