name: Publish SMM635 Website

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'
          use-public-rspm: true

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install minimal R dependencies
        run: |
          install.packages(c('rmarkdown', 'knitr'))
        shell: Rscript {0}

      - name: Render Quarto site (HTML only, skip PDF generation)
        run: |
          cd website
          # Temporarily rename PDF output to skip PDF generation for syllabus
          mv course/syllabus.qmd course/syllabus.qmd.bak
          # Create HTML-only version of syllabus
          sed '/^  pdf:/,/^[[:space:]]*[^[:space:]]/d' course/syllabus.qmd.bak > course/syllabus.qmd

          # Remove Beamer format from presentations to skip PDF generation in CI
          python3 -c '
          import re
          import glob

          for pattern in ["weeks/week-*/design-principles-presentation.qmd", "weeks/week-*/gog_and_visual_forms.qmd"]:
              for filepath in glob.glob(pattern):
                  with open(filepath, "r") as f:
                      content = f.read()

                  # Backup
                  with open(filepath + ".bak", "w") as f:
                      f.write(content)

                  # Remove beamer section
                  content = re.sub(r"^  beamer:.*?\n(?=^(?:\S|---))", "", content, flags=re.MULTILINE | re.DOTALL)

                  with open(filepath, "w") as f:
                      f.write(content)
          '

          # Render the site
          quarto render --no-execute

          # Restore the original files
          mv course/syllabus.qmd.bak course/syllabus.qmd
          for backup in weeks/week-*/*.qmd.bak; do
            if [ -f "$backup" ]; then
              original="${backup%.bak}"
              mv "$backup" "$original"
            fi
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4